version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_app
    volumes:
      - ./:/var/www
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - APP_ENV=local
      - APP_KEY=base64:OFFt9LUfICGigLqXzcx6xKP1iVY+e0U9Pm9NRyey+Go=
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres123
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: laravel_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=laravel
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
